name: CI pipeline
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: yarn
      - name: build code
        run: yarn build
      - name: pull request front-end preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          preview-branch: main
          umbrella-dir: pr-preview
          action: auto
# add comments
